### PR TITLE
[travis] enable ocra modules compilation

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
Testing travis response before merging.

**Comment by traversaro** [comment]
Depends on https://github.com/ocra-recipes/ocra-recipes/pull/1 and https://github.com/ocra-recipes/ocra-recipes/pull/2 .

**Comment by rlober** [comment]
This should work now...

**Comment by traversaro** [comment]
Restarted the build now.

**Comment by traversaro** [comment]
Clang on Linux is failing, but I think it is due to some bug in the old Boost version, because on my Ubuntu 14.04 is working fine. 

Clang on OS X is also failing, but for some issue related to linking. It is probably trivial, but I will need to an OS X machine to debug this problem.

**Comment by rlober** [comment]
Ok, let me know if I can help in any way.

**Comment by traversaro** [comment]
For the time being, we will test the ocra software compilation just on Linux/gcc  (as done in https://github.com/robotology/codyco-superbuild/commit/54c02a571933b1297ee5b6eab50bb1bc9928da87 ). For compilation enabled by default on both Linux and OS X https://github.com/ocra-recipes/ocra-recipes/issues/4 needs to be solved.

**Pull request merged**
