### PR TITLE
Test against xcode7.3 on Travis

### PR DESCRIPTION
**Pull request by traversaro**
Try to fix the octave related issues by using a recent OS X version

### CODE REVIEW

**Comment by traversaro** [comment]
@francesco-romano Given https://github.com/Homebrew/brew/issues/1056 , do you think it make sense to drop Travis support for OS X 10.9 and just test against 10.10 (and eventually 10.11?).

**Comment by francesco-romano** [comment]
I had a talk with @drdanz about this a month ago (more or less) saying that it would be nice to test our software on more than one macOS version at a time.
Unfortunately we agreed that not only the build matrix would explode, but also the time to have a job finished. The best thing would be to have these tests on our (local) dashboard.

Anyway, if you read here: https://blog.travis-ci.com/2016-09-15-new-default-osx-image-coming they state that on Monday they will switch the default to Xcode 7.3 @10.11 and that macOS < 10.10 won't be supported anymore.

Anyway, considering how software on macOS works, the best thing we can do (IMHO) is to support the current and the previous version of Xcode&macOS, i.e. Xcode8@10.12 and Xcode7.3@10.11

**Comment by traversaro** [comment]
Perfect.

**Comment by jeljaik** [comment]
I didn't report this but I already had troubles compiling codyco-superbuild
with XCode 8. I then had to downgrade. Have you guys tried?

**Comment by traversaro** [comment]
Yes, the problem everyone is having is related to the compilation of ace on 10.12, see https://github.com/Homebrew/homebrew-core/issues/3639 .

**Comment by jeljaik** [comment]
Exactly.

**Comment by francesco-romano** [comment]
If I did the things right, the master branch of ACE is already fixed to work on macOS 10.12 (and/or Xcode 8.0). Unfortunately they have not released any new version yet.
So, either we wait for them to provide a release, or we have to manually compile ACE.
I'll probably try to provide an alternative brew formula, but this takes a lot of time and I don't have it right now.

**Comment by claudiofantacci** [comment]
Why don't we literally ask them to release 6.5.1 to fix Xcode8/Sierra compilation bug?
I'll might give it a try soon. Eventually, the will gtfo me 😆

**Comment by francesco-romano** [comment]
well... patch submitted to brew.
@claudiofantacci, @jeljaik or @vtikha  do you have Sierra installed to test it?

**Comment by traversaro** [comment]
:+1:

**Comment by claudiofantacci** [comment]
I didn't upgrade because my MATLAB is not supported by Sierra yet (there is a bug with the new locale settings of Sierra).

I will eventually ask for a 6.4.1 to the DOCGroup.

**Comment by jeljaik** [comment]
I have sierra and matlab is working well. They released a patch only if you
have 2016a or 2016b which I have.

**Comment by claudiofantacci** [comment]
I have Italian system language and according to this bugreport http://www.mathworks.com/support/bugreports/1465823 my version, R2015a, is affected by this problem. They recently release a fix for R2015b. Hopefully I will also have a patch soon.

**Comment by vtikha** [comment]
Some updates: with @francesco-romano we tried the patch getting an `malformed end of line` but removing the trailing white spaces in the formula allows ace to be successfully compiled. I also compiled yarp and it all works fine.

**Comment by francesco-romano** [comment]
If someone want to test it: https://github.com/Homebrew/homebrew-core/pull/5476

**Comment by claudiofantacci** [comment]
Meanwhile I wrote to ace-users mailing list for a possible 6.4.1 of ACE.
Let's see what happens 😂

**Comment by traversaro** [comment]
In the past they have been also responsive on ACE's Github repo : https://github.com/DOCGroup/ACE_TAO/issues .

**Comment by claudiofantacci** [comment]
True that, but from my understanding they prefer the official mailing list.
Let's see, eventually I will write them again via GH issue.

**Comment by claudiofantacci** [comment]
[Got an answer already!](https://github.com/Homebrew/homebrew-core/issues/3639#issuecomment-250923676)

**Comment by jeljaik** [comment]
I just wanted to let you know guys that I have installed Xcode 8.2 and successfully compiled Yarp and codyco-superbuild.

**Pull request merged**
