### PR TITLE
Update task managers and task seq…

### PR DESCRIPTION
**Pull request by alexandrelheinen**
…uence at ISIR modules.

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks for the readme change @alexandrelheinen ! 
Before merging can you check to include only the readme change and don't include the other changes? 
Unfortunatly there is an incompatibility between `codyco-modules` and `ocra-wbi-plugins` due to conflicting Eigen requirements, so we agreed with @rlober that for now by default the codyco-superbuild will install the codyco-module.
Feel free to open a new pull request for committing just the README.md modifications.

**Comment by alexandrelheinen** [comment]
Hi @traversaro,

first at all sorry for this commit, actually it was the first time I used terminal git commands and I think I just mess the hole thing. I was actually just trying to fork this repository to work on it during my internship at ISIR and not to commit directly on your main repository (shame on me), because I needed to made some changes in ISIR Modules' codes, otherwise it wouldn't compile on my PC. Anyway I think it is done now.

Again sorry about this trouble.

Just a last question, the changes I made in my forked repository have no influence on robotology:master, isn't it? Otherwise I'm really, really sorry, because I just wanted to "play" with the codes and adapt them to my needs.

**Comment by alexandrelheinen** [comment]
It just means that your can close this commit, just ignore it.

Thanks.

**Comment by traversaro** [comment]
Don't worry @alexandrelheinen , you did not made any change to the codyco-superbuild!

**Pull request closed without merging**
